### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('f...

### ISSUE THREAD

**Issue by nadeemja** [varemenos/atom-toolbar-almighty#17] opened 2016-07-04 08:56 UTC
Please see https://github.com/suda/tool-bar/issues/148

**Comment by varemenos** [comment] 2016-07-04 12:24
Thanks for reporting this, unfortunately I'm currently serving my mandatory military service and I won't be able to return home and fix it this month. I'm really sorry for the inconvenience but I only have access to a smartphone and have limited amount of time.
Once I get some time off hopefully in the beginning of August I will go ahead and update + fix the package. Hope you can survive for now with the modified local copy of the package

**Comment by nadeemja** [comment] 2016-07-04 12:56
I will survive. Let's hope you do too :p

**Comment by NexusInk** [comment] 2016-07-04 15:01
`packages/atom-tool-bar-almighty/lib/entries.coffee`
In line 60:
delete 'column' from `icon: 'column fa-rotate-270'`

**Comment by NexusInk** [comment] 2016-07-04 15:01
Kalos politis...

**Comment by varemenos** [comment] 2016-08-09 11:00
I will start working on this tomorrow so expect a fix soon.
Sorry for the delay people, hopefully it will worth the wait

**Comment by varemenos** [comment] 2016-08-10 22:17
The issue is fixed with the release of [v0.7](https://github.com/varemenos/atom-toolbar-almighty/releases/tag/v0.7.0).
If you still have problems please inform me so I can reopen the issue.

**Closed as completed** 2016-08-10 22:18 UTC
Labels: bug
